package br.com.byop.aionlogbook.shared.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    TOKEN_EXPIRED,
    FORBIDDEN,
    INVALID_REQUEST_PARAMETER,
    RESOURCE_NOT_FOUND,
    INVALID_TRANSITION,
    BUSINESS_RULE_VIOLATION,
    CONFLICT,
    INTERNAL_ERROR
}
